image: mcr.microsoft.com/azure-cli

pipelines:
    default:
    - step:
        script:
        - |
            ls -al
            az login --service-principal -u 956c8136-2553-4d38-b63b-41f931323cf0 -p PokFUeGH4v6QvfQ04.JqTHRycA53BCcety -t 476b320f-8c9c-46cb-8856-624a5d3c2c2c
            az storage blob upload-batch -s . -d '$web' --account-name cs4100320011789b4aa
